qsub: qsub
python_path: /home/shared/anaconda3/envs/CCpy/bin/python
mpi_run: mpirun
atk_mpi_run: /opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/intel64/bin/mpirun
vasp_path: /opt/vasp/vasp.5.4.1/bin/vasp_std
g09_path: g09
atk_path: /opt/Quantumwise/VNL-ATK-2019.12SP1/bin/atkpython
lammps_path: lmp_g++
siesta_path: siesta
